using Iconnect.Aplicacao.Interfaces;

namespace Iconnect.Aplicacao
{
    public interface IServiceWrapper
    {
        public IClienteService Cliente { get; }
        public IAcessoService Acesso { get; }
        public IEmpresaService Empresa { get; }
        public IFotoEmpresaService FotoEmpresa { get; }
        public IRacaService Raca { get; }
        public IPerfilService Perfil { get; }
        public IMarcaVeiculoService MarcaVeiculo { get; }
        public IPermissionamentoService Permissionamento { get; }
        public ICategorizacaoEventoService CategorizacaoEvento { get; }
        public ICategorizacaoAvisoService CategorizacaoAviso { get; }
        public ILimpezaClienteService LimpezaCliente { get; }
        public IOperadorLocalService OperadorLocal { get; }
        public IGrupoPermissaoOperadorService GrupoPermissaoOperador { get; }
        public IGrupoVagasService GrupoVagas { get; }
        public IProprietarioService Proprietario { get; }
        public IEstadoService Estado { get; }
        public ICidadeService Cidade { get; }
        public ICepService Cep { get; }
        public IModuloService Modulo { get; }
        public IAvisoEmpresaService AvisoEmpresa { get; }
        public IAvisoService Aviso { get; }
        public IEnvioNotificacaoService EnvioNotificacao { get; }
        public IOperadorService Operador { get; }
        public IMoradorService Morador { get; }
        public IGrupoFamiliarService GrupoFamiliar { get; }
        public INotificacaoAppService NotificacaoApp { get; }
        public IUploadAPKService UploadAPK { get; }
        public IZeladorClienteService ZeladorCliente { get; }
        public IEquipamentoClienteService EquipamentoCliente { get; }
        public IPgmService Pgm { get; }
        public ICabecalhoLayoutService CabecalhoLayout { get; }
        public IZoneamentoClienteService ZoneamentoCliente { get; }
        public IVigilanteClienteService VigilanteCliente { get; }
        public IMotivoOcorrenciaService MotivoOcorrencia { get; }
        public IDispositivoCFTVService DispositivoCFTV { get; }
        public IRamalLayoutService RamalLayout { get; }
        public IPontosAcessoService PontosAcesso { get; }
        public IMapeamentoPontoAcessoService MapeamentoPontoAcesso { get; }
        public ILocalidadeClienteService LocalidadeCliente { get; }
        public IPermissaoClienteService PermissaoCliente { get; }
        public ILicencasService Licencas { get; }
        public ILayoutService Layout { get; }
        public ICanalLayoutService CanalLayout { get; }
        public IEmailService Email { get; }
        public IMonitoramentoService Monitoramento { get; }
        public IDisparoPgmService DisparoPgm { get; }
        public IVisitanteService Visitante { get; }
        public IPrestadorServicoService PrestadorServico { get; }
        public IPessoaService Pessoa { get; }
        public IControladoraService Controladora { get; }
        public IPerfilHorarioService PerfilHorario { get; }
        public IPermissoesGrupoService PermissoesGrupo { get; }
        public IResponsavelLocacaoService ResponsavelLocacao { get; }
        public IDependenciasService Dependencias { get; }
        public IFotoDependenciaService FotoDependencia { get; }
        public IArquivoDependenciaService ArquivoDependencia { get; }
        public IAvisoGrupoFamiliarService AvisoGrupoFamiliar { get; }
        public IPetService Pet { get; }
        public IVeiculoService Veiculo { get; }
        public IRegistroSalaoService RegistroSalao { get; }
        public IControleAcessoService ControleAcesso { get; }
        public IHorarioService Horario { get; }
        public IMonitoramentoControleAcessoService MonitoramentoControleAcesso { get; }
        public ISolicitacaoAberturaRemotaService SolicitacaoAberturaRemota { get; }
        public IPessoasRecintoService PessoasRecinto { get; }
        public ISincronizacaoPlacasService SincronizacaoPlacas { get; }
        public IAfastamentoService Afastamento { get; }
        public IFotoService Foto { get; }
        public IFrotaService Frota { get; }
        public IMovimentacaoVeiculoService MovimentacaoVeiculo { get; }
        public IDocumentoService Documento { get; }
        public IDocumentoMoradorService DocumentoMorador { get; }
        public IDuvidasAppService DuvidasApp { get; }
        public ISolicitarZeladorService SolicitarZelador { get; }
        public IInformacoesClienteService InformacoesCliente { get; }
        public IAtendimentoService Atendimento { get; }
        public IDashboardService Dashboard { get; }
        public ISegurancaService SegurancaService { get; }
        public IUsuarioAppService UsuarioApp { get; }
        public IHistoricoLiberacaoService HistoricoLiberacao { get; }
        public INotificacaoService Notificacao { get; }
        public IConnectionSignalRService ConnectionSignalR { get; }
        public ICatalogoService Catalogo { get; }
        public ICategoriaCatalogoService CategoriaCatalogo { get; }
        public ISubCategoriaCatalogoService SubCategoriaCatalogo { get; }
        public IPrecosService Precos { get; }
        public IRefeicaoService Refeicao { get; }
        public IDistribuidorService Distribuidor { get; }
        public IAgendaService Agenda { get; }
        public IVisitanteAppService VisitasApp { get; }
        public IUsuarioSalaComercialService UsuarioSalaComercial { get; }
        public IAgenteComercialService AgenteComercial { get; }
        public ILocalidadeGrupoFamiliarService LocalidadeGrupoFamiliar { get; }
        public IParametrosEmpresaService ParametrosEmpresa { get; }
        public IRamalOperadorService RamalOperador { get; }
        public IOcorrenciasOperadorService OcorrenciasOperador { get; }
        public IAjudaService Ajuda { get; }
        public ITopicosService Topicos { get; }
    }
}