name: Deploy new feature in master
on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2 master
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME : "ec2-3-83-42-207.compute-1.amazonaws.com"
          USER_NAME : "ubuntu"

        run: |
          sudo apt-get update
          sudo apt-get install openssh-client -y
          '
      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your.ec2.instance.ip >> ~/.ssh/known_hosts      