name: Deploy new feature in master
on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2 master
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME : "ec2-54-197-67-58.compute-1.amazonaws.com"
          USER_NAME : "ubuntu"
          TARGET: "/var/www/html/iconnect/"
          REMOTE_HOST: "ec2-54-197-67-58.compute-1.amazonaws.com"
        run: |
          sudo apt-get update
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          //install nodejs
          sudo apt-get install -y nodejs
          npm install -g @angular/cli > /dev/null 
          //install git
          sudo apt-get install git
          //clone project
          git clone https://github.com/fabianolaudutra/iconnect.git
          //install dependencies
          npm install
          //run project
          //install nginx
          sudo apt-get install nginx
          //copy nginx config
          sudo cp /home/ubuntu/your-project/nginx.conf /etc/nginx/sites-available/default
          //restart nginx
          sudo systemctl restart nginx
          '
     