name: Deploy new feature in master

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Deploy in EC2 master
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME : "ec2-54-243-19-243.compute-1.amazonaws.com"
          USER_NAME : "ec2-user"

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            pwd &&
            cd /home/ubuntu/app/iconnect &&
            git pull --rebase &&
            docker stop $(docker ps -a -q) &&
            docker rm $(docker ps -a -q) &&
            docker build --no-cache --build-arg NODE_ENV=develop -t iconnect:latest -f docker/nodejs/Dockerfile . &&
            docker stop iconnect > /dev/null 2>&1 && echo 'container parado' || echo 'container n existe' &&
            docker system prune -f &&
            docker run --restart on-failure --env-file appsettings.Development.json -p 3000:3000 -d --name=iconnect iconnect:latest
          '